services:
  gateway:
    build:
      context: ./gateway
    volumes:
      - ./gateway/src:/app/src
    ports:
      - 5000:5000
  servicea:
    build:
      context: ./servicea
    volumes:
      - ./servicea/src:/app/src
  serviceb:
    build:
      context: ./serviceb
    volumes:
      - ./serviceb/src:/app/src
